// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLAY3wnthrP6BVRtSux_x0_MMgoWnUtw',
    appId: '1:217147279305:web:402c90de932fb7be95ca18',
    messagingSenderId: '217147279305',
    projectId: 'chat-app-3a2c9',
    authDomain: 'chat-app-3a2c9.firebaseapp.com',
    storageBucket: 'chat-app-3a2c9.appspot.com',
    measurementId: 'G-NQ6Q893B6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOeg8uHbNv9rWbjwhR3Ua1CKPajeAlayU',
    appId: '1:217147279305:android:64c03582ad299a6695ca18',
    messagingSenderId: '217147279305',
    projectId: 'chat-app-3a2c9',
    storageBucket: 'chat-app-3a2c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2rFIk60GWPT3frncFTkiT5quTHKx5Ups',
    appId: '1:217147279305:ios:cd3af5500fdf0b9395ca18',
    messagingSenderId: '217147279305',
    projectId: 'chat-app-3a2c9',
    storageBucket: 'chat-app-3a2c9.appspot.com',
    iosBundleId: 'com.example.chatapp`',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyLAY3wnthrP6BVRtSux_x0_MMgoWnUtw',
    appId: '1:217147279305:web:34bdcf59a434708f95ca18',
    messagingSenderId: '217147279305',
    projectId: 'chat-app-3a2c9',
    authDomain: 'chat-app-3a2c9.firebaseapp.com',
    storageBucket: 'chat-app-3a2c9.appspot.com',
    measurementId: 'G-EFL5V5PV21',
  );
}
